### ISSUE TITLE
Option to disable strings as factors

### ISSUE THREAD

**Issue by rpodcast** [BioStatMatt/sas7bdat.parso#1]
Hello Matt, I want to say thank you very much for creating this package!  I've been testing it out and one feature I would like to request is to give the user an option to not have all strings converted to factors during the import process.  Would you be able to give `read.sas7bdat.parso` an additional argument such as `stringsAsFactors` much like the typical `read.table` family of functions?

Regards,
Eric

**Comment by BioStatMatt** [comment]
Eric,

The current implementation first converts the sas7bdat file to temporary
CSV, then uses read.csv to read into R. I've added a '...' to the
read.sas7bdat.parso function so that you can pass additional arguments to
read.csv (including stringsAsFactors). I think that should do it.

Best,
Matt

**Comment by xiaodaigh** [comment]
I think this issue should be closed

**Comment by BioStatMatt** [comment]
Agreed.
